name: Contribution Check - Git Inspector

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install
      run: sudo apt-get install gitinspector
    - name: Git Insceptor
      run: gitinspector --enable=all 3_Implementation
   
